
" Highlight in red spaces by itself
function ShowSpaces(...)
  let @/='\v(\s+$)|( +\ze\t)'
  let oldhlsearch=&hlsearch
  if !a:0
    let &hlsearch=!&hlsearch
  else
    let &hlsearch=a:1
  end
  return oldhlsearch
endfunction
command -bar -nargs=? ShowSpaces call ShowSpaces(<args>)

" Automatically remove spaces in Python
autocmd BufWritePre *.py :%s/\s\+$//e


" Make the # vim: set ts=4 sw=4 et sts=4 ai: lines work.
set modelines=5
set modeline
