" Don't run in vim mode
set nocompatible

" Default options
colorscheme darkblue
syntax on
set spell
set number
set hlsearch

" Disable toolbar in the gui
set guioptions-=T

" Highlight in red extra whitespace
" http://vim.wikia.com/wiki/Highlight_unwanted_spaces
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Make the # vim: set ts=4 sw=4 et sts=4 ai: lines work.
set modelines=5
set modeline

" Persistent undo
set undodir=~/.vim/undodir

" Default formatting style and overrides for given types.
au BufNewFile,BufRead *.py setlocal et ts=4 sw=4 sts=4
au BufNewFile,BufRead *.go setlocal noet ts=4 sw=4 sts=4
au BufNewFile,BufRead *.h setlocal et ts=4 sw=4 sts=4
au BufNewFile,BufRead *.cc setlocal et ts=4 sw=4 sts=4
au BufNewFile,BufRead *.cpp setlocal et ts=4 sw=4 sts=4

" Setup pathogen
source ~/rcfiles/vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('~/rcfiles/vim/bundle/{}')

" Extra plugin configuration
source ~/rcfiles/vim/go.vim
source ~/rcfiles/vim/gotags.vim
source ~/rcfiles/vim/syntastic.vim
source ~/rcfiles/vim/statusline.vim

" Turn on plugins
filetype plugin indent on
