colorscheme darkblue
syntax on
set spell
set number
set hlsearch

" Highlight in red spaces by itself
function ShowSpaces(...)
  let @/='\v(\s+$)|( +\ze\t)'
  let oldhlsearch=&hlsearch
  if !a:0
    let &hlsearch=!&hlsearch
  else
    let &hlsearch=a:1
  end
  return oldhlsearch
endfunction
command -bar -nargs=? ShowSpaces call ShowSpaces(<args>)

" Make the # vim: set ts=4 sw=4 et sts=4 ai: lines work.
set modelines=5
set modeline

" Persistent undo
set undodir=~/.vim/undodir
