#!/bin/sh

function ls {
	LS=`which ls`
	LINES=`$LS $@ 2> /dev/null | wc -l`
	if [ $LINES  -gt 100 ]; then
		echo "Output greater then 100 lines, still show? [N]:"
		read show
		case $show in
			Y*)
				;;
			y*)
				$LS $@
				;;
			*)
				;;
		esac
	else
		$LS $@
	fi
}
