#! /bin/sh

# Make rm a little safer
alias rm="rm -i"

# Better ls support
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# Make PS nicer.
alias ps="ps fax"

# Give me vim
alias vi=vim
alias vim=vim
alias vimdiff=vimdiff
export EDITOR="vim"
case "$TERM" in
  screen*|xterm*)
    # Gvim when running under X
    if [ -x /usr/bin/gvim ]; then
      export UBUNTU_MENUPROXY=
      alias vi=gvim
      alias vim=gvim
      alias vimdiff=gvimdiff
      export EDITOR="gvim -f"
    fi
    ;;
  *)
    # Just normal vim when running on shell
    ;;
esac

alias emacs=vi	# Confuse other people using my system

# Getting around faster
alias ..='cd ..'
alias ~='cd ~'
alias ...='cd ../..'
function p {
 if [ x$1 == x ]; then
   popd
 else
   pushd $1
 fi
}

# git aliases
alias gitk="gitk --all"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Ack is a tool like grep which makes life easier
if [ -x "/usr/bin/ack-grep" ]; then
  # Use color for ack
  export ACK_COLOR_FILENAME="bold blue"
  export ACK_COLOR_MATCH="bold red"
  alias ack='ack-grep --color'
  alias hl='ack --color --passthru --flush'
  alias logcolor='ACK_COLOR_MATCH="bold red" hl "ERROR.*" | ACK_COLOR_MATCH="bold purple" hl "WARN.*"'
fi

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Tools which need to be run as root
# Check for "install" in the cmd line, run with sudo then.
alias apt-get="sudo apt-get"

# Google specific alias
alias g3='test -d google3 && echo google3 || pwd | sed "s,^\(.*\)google3.*$,\1google3,"'
alias cdg='cd $(g3)'
alias cdr='cd $(pwd | sed -e"s,google3,READONLY/google3," -e"s,READONLY/READONLY,,")'
alias cdw='cd $(pwd | sed -e"s,google3,review/$(git symbolic-ref HEAD | sed -e's-.*/--')/google3," -e"s,review/.*/review/[^/]*/,,")'
alias cdj='cdg; cd java/com/google'
alias cdjt='cdg; cd javatests/com/google'
alias szl=/home/build/static/projects/logs/szl
alias prodaccess='prodaccess -f'

alias less="less -R"

# Bigger command aliases / functions
for include in ~/rcfiles/bash/include/*; do
  source $include
done
